"use client";

import Link from "next/link";
import { DONATION_PATH, FOUNDER_FEEDBACK_URL } from "@/lib/config";
import { useLocale, useUiCopy } from "@/components/i18n/LocaleProvider";

type FooterLink = { label: string; href: string; external?: boolean };

const links: Record<"de" | "en" | "tr", readonly { title: string; links: readonly FooterLink[] }[]> = {
  de: [
    { title: "Nutzen", links: [{ label: "Der Guide", href: "/guide" }, { label: "Beispiele", href: "/beispiele" }, { label: "Tipps", href: "/tipps" }, { label: "Warum ein Brief?", href: "/warum-ein-brief" }, { label: "Brief schreiben wirkt: erste Ergebnisse", href: "/brief-schreiben-wirkt" }, { label: "Studien zur Wirkung", href: "/handschriftliche-briefe-wirkung" }, { label: "Treppe der Selbstwirksamkeit", href: "/treppe-der-selbstwirksamkeit" }, { label: "Wer darf MdBs schreiben?", href: "/wer-darf-mdb-schreiben" }] },
    { title: "Projekt", links: [{ label: "Wer dahintersteht", href: "/warum" }, { label: "KI & Transparenz", href: "/ki-transparenz" }, { label: "Andere Demokratie-Tools", href: "/andere-tools" }, { label: "Was bisher geschah", href: "/was-bisher-geschah" }, { label: "Was noch kommt", href: "/was-noch-kommt" }, { label: "Lage der Nation", href: "/lage-der-nation" }, { label: "Presse", href: "/presse" }] },
    { title: "Mitmachen", links: [{ label: "Feedback", href: FOUNDER_FEEDBACK_URL, external: true }, { label: "Weitersagen", href: "/weitersagen" }, { label: "Briefkampagnen für NGOs", href: "/ngo-briefkampagne" }, { label: "Kampagne starten", href: "/kampagne/starten" }, { label: "Open Source", href: "https://github.com/tholo91/brief-nach-berlin", external: true }, { label: "Europa", href: "/europe" }] },
    { title: "Rechtliches", links: [{ label: "Impressum", href: "/impressum" }, { label: "Datenschutz", href: "/datenschutz" }] },
  ],
  en: [
    { title: "Use", links: [{ label: "Guide", href: "/guide" }, { label: "Examples", href: "/beispiele" }, { label: "Tips", href: "/tipps" }, { label: "Why a letter?", href: "/warum-ein-brief" }, { label: "First results", href: "/brief-schreiben-wirkt" }, { label: "Research on impact", href: "/handschriftliche-briefe-wirkung" }, { label: "Self-efficacy ladder", href: "/treppe-der-selbstwirksamkeit" }, { label: "Who may write to MPs?", href: "/wer-darf-mdb-schreiben" }] },
    { title: "Project", links: [{ label: "About the project", href: "/warum" }, { label: "AI & transparency", href: "/ki-transparenz" }, { label: "Other democracy tools", href: "/andere-tools" }, { label: "Project history", href: "/was-bisher-geschah" }, { label: "What is next", href: "/was-noch-kommt" }, { label: "State of the nation", href: "/lage-der-nation" }, { label: "Press", href: "/presse" }] },
    { title: "Get involved", links: [{ label: "Feedback", href: FOUNDER_FEEDBACK_URL, external: true }, { label: "Spread the word", href: "/weitersagen" }, { label: "Letter campaigns for NGOs", href: "/ngo-briefkampagne" }, { label: "Start a campaign", href: "/kampagne/starten" }, { label: "Open source", href: "https://github.com/tholo91/brief-nach-berlin", external: true }, { label: "Europe", href: "/europe" }] },
    { title: "Legal", links: [{ label: "Legal notice", href: "/impressum" }, { label: "Privacy policy", href: "/datenschutz" }] },
  ],
  tr: [
    { title: "Kullanım", links: [{ label: "Rehber", href: "/guide" }, { label: "Örnekler", href: "/beispiele" }, { label: "İpuçları", href: "/tipps" }, { label: "Neden mektup?", href: "/warum-ein-brief" }, { label: "İlk sonuçlar", href: "/brief-schreiben-wirkt" }, { label: "Etkisine dair araştırmalar", href: "/handschriftliche-briefe-wirkung" }, { label: "Öz yeterlilik merdiveni", href: "/treppe-der-selbstwirksamkeit" }, { label: "Milletvekillerine kim yazabilir?", href: "/wer-darf-mdb-schreiben" }] },
    { title: "Proje", links: [{ label: "Proje hakkında", href: "/warum" }, { label: "Yapay zekâ ve şeffaflık", href: "/ki-transparenz" }, { label: "Diğer demokrasi araçları", href: "/andere-tools" }, { label: "Proje geçmişi", href: "/was-bisher-geschah" }, { label: "Sırada ne var", href: "/was-noch-kommt" }, { label: "Ulusun durumu", href: "/lage-der-nation" }, { label: "Basın", href: "/presse" }] },
    { title: "Katılın", links: [{ label: "Geri bildirim", href: FOUNDER_FEEDBACK_URL, external: true }, { label: "Paylaşın", href: "/weitersagen" }, { label: "STK'lar için mektup kampanyaları", href: "/ngo-briefkampagne" }, { label: "Kampanya başlat", href: "/kampagne/starten" }, { label: "Açık kaynak", href: "https://github.com/tholo91/brief-nach-berlin", external: true }, { label: "Avrupa", href: "/europe" }] },
    { title: "Yasal", links: [{ label: "Yasal bilgiler", href: "/impressum" }, { label: "Gizlilik politikası", href: "/datenschutz" }] },
  ],
};

export function LocalizedFooter({ letterCount, formattedLetterCount }: { letterCount: number; formattedLetterCount: string }) {
  const { locale } = useLocale();
  const copy = useUiCopy();
  return <footer className="bg-creme"><div className="h-2 w-full" style={{ background: "repeating-linear-gradient(-45deg,var(--color-airmail-rot),var(--color-airmail-rot) 8px,var(--color-creme) 8px,var(--color-creme) 12px,var(--color-airmail-blau) 12px,var(--color-airmail-blau) 20px,var(--color-creme) 20px,var(--color-creme) 24px)" }} /><div className="max-w-5xl mx-auto px-6 py-10 flex flex-col gap-8"><div className="grid gap-8 md:grid-cols-[1.2fr_3fr]"><div><p className="font-typewriter text-sm font-bold tracking-widest uppercase text-waldgruen/50 mb-3">Brief-nach-Berlin</p><p className="font-body text-sm leading-relaxed text-warmgrau/65 max-w-sm">{copy.footer.description}</p></div><nav aria-label={copy.footer.navigationAriaLabel} className="grid grid-cols-2 lg:grid-cols-4 gap-x-8 gap-y-8">{links[locale].map((section) => <div key={section.title}><h2 className="font-typewriter text-xs font-bold tracking-widest uppercase text-waldgruen/50 mb-3">{section.title}</h2><ul className="space-y-2.5">{section.links.map((link) => <li key={link.href}>{link.external ? <a href={link.href} target="_blank" rel="noopener noreferrer" className="font-body text-sm text-warmgrau/70 hover:text-waldgruen-dark transition-colors duration-200">{link.label}</a> : <Link href={link.href} prefetch={false} className="font-body text-sm text-warmgrau/70 hover:text-waldgruen-dark transition-colors duration-200">{link.label}{locale !== "de" && <span className="sr-only"> ({copy.footer.germanPageSuffix})</span>}</Link>}</li>)}</ul></div>)}</nav></div><div className="border-t border-warmgrau/10 pt-6 flex flex-col sm:flex-row items-center justify-between gap-4"><span className="font-typewriter text-sm text-warmgrau/40">Brief-nach-Berlin &copy; {new Date().getFullYear()}{letterCount > 0 && <span className="ml-1"> · {copy.footer.letterCount.replace("{count}", formattedLetterCount)}</span>}</span><div className="flex items-center gap-4"><Link href={DONATION_PATH} prefetch={false} className="font-body text-sm font-semibold text-waldgruen hover:text-waldgruen-dark transition-colors duration-200">{copy.footer.support}</Link><Link href="/app" prefetch={false} className="font-body text-sm text-warmgrau/40 hover:text-warmgrau transition-colors duration-200">{copy.footer.writeLetter}</Link></div></div></div></footer>;
}
